export default [
  {
    car_name: "Audi",
    cost: 73341,
    model: "Hatchback",
    manufacturer: "Porsche",
    color: "Orange",
    num_doors: 3,
    cylinder_capacity: 6751,
    fuel_type: "Hybrid",
    transmission: "Automatic",
    drive_type: "All-wheel drive",
    horsepower: 941,
  },
  {
    car_name: "Porsche",
    cost: 61169,
    model: "Hatchback",
    manufacturer: "Tesla",
    color: "Red",
    num_doors: 4,
    cylinder_capacity: 6719,
    fuel_type: "Hybrid",
    transmission: "Manual",
    drive_type: "All-wheel drive",
    horsepower: 230,
  },
  {
    car_name: "Porsche",
    cost: 73467,
    model: "Wagon",
    manufacturer: "Ford",
    color: "Black",
    num_doors: 2,
    cylinder_capacity: 7641,
    fuel_type: "Diesel",
    transmission: "Manual",
    drive_type: "Front-wheel drive",
    horsepower: 862,
  },
  {
    car_name: "Mercedes-Benz",
    cost: 98089,
    model: "Sedan",
    manufacturer: "Honda",
    color: "Red",
    num_doors: 2,
    cylinder_capacity: 5307,
    fuel_type: "Hybrid",
    transmission: "Manual",
    drive_type: "Rear-wheel drive",
    horsepower: 787,
  },
  {
    car_name: "Audi",
    cost: 56099,
    model: "Sedan",
    manufacturer: "Audi",
    color: "Purple",
    num_doors: 3,
    cylinder_capacity: 7276,
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drive_type: "Front-wheel drive",
    horsepower: 72,
  },
  {
    car_name: "Tesla",
    cost: 75633,
    model: "Wagon",
    manufacturer: "Porsche",
    color: "Green",
    num_doors: 3,
    cylinder_capacity: 3460,
    fuel_type: "Diesel",
    transmission: "Manual",
    drive_type: "All-wheel drive",
    horsepower: 743,
  },
  {
    car_name: "BMW",
    cost: 45546,
    model: "SUV",
    manufacturer: "Ford",
    color: "Red",
    num_doors: 3,
    cylinder_capacity: 2304,
    fuel_type: "Hybrid",
    transmission: "Automatic",
    drive_type: "Front-wheel drive",
    horsepower: 93,
  },
  {
    car_name: "Ford",
    cost: 70265,
    model: "Truck",
    manufacturer: "Mercedes-Benz",
    color: "Gray",
    num_doors: 3,
    cylinder_capacity: 5926,
    fuel_type: "Diesel",
    transmission: "Automatic",
    drive_type: "Front-wheel drive",
    horsepower: 327,
  },
  {
    car_name: "Tesla",
    cost: 35351,
    model: "Hatchback",
    manufacturer: "Chevrolet",
    color: "Green",
    num_doors: 4,
    cylinder_capacity: 5741,
    fuel_type: "Electric",
    transmission: "Automatic",
    drive_type: "All-wheel drive",
    horsepower: 896,
  },
  {
    car_name: "Honda",
    cost: 68686,
    model: "SUV",
    manufacturer: "Tesla",
    color: "Orange",
    num_doors: 5,
    cylinder_capacity: 2319,
    fuel_type: "Electric",
    transmission: "Automatic",
    drive_type: "Rear-wheel drive",
    horsepower: 244,
  },
  {
    car_name: "Toyota",
    cost: 65880,
    model: "Sedan",
    manufacturer: "Toyota",
    color: "Silver",
    num_doors: 2,
    cylinder_capacity: 3420,
    fuel_type: "Diesel",
    transmission: "Automatic",
    drive_type: "Rear-wheel drive",
    horsepower: 385,
  },
  {
    car_name: "Ford",
    cost: 23102,
    model: "Wagon",
    manufacturer: "Honda",
    color: "Black",
    num_doors: 4,
    cylinder_capacity: 5630,
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drive_type: "All-wheel drive",
    horsepower: 292,
  },
  {
    car_name: "Mercedes-Benz",
    cost: 52532,
    model: "Convertible",
    manufacturer: "Ford",
    color: "Gray",
    num_doors: 3,
    cylinder_capacity: 2191,
    fuel_type: "Electric",
    transmission: "Automatic",
    drive_type: "Rear-wheel drive",
    horsepower: 588,
  },
  {
    car_name: "Tesla",
    cost: 29208,
    model: "Wagon",
    manufacturer: "Ford",
    color: "Yellow",
    num_doors: 3,
    cylinder_capacity: 5418,
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drive_type: "Rear-wheel drive",
    horsepower: 707,
  },
  {
    car_name: "Nissan",
    cost: 44517,
    model: "Truck",
    manufacturer: "Tesla",
    color: "Red",
    num_doors: 4,
    cylinder_capacity: 2959,
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drive_type: "All-wheel drive",
    horsepower: 498,
  },
  {
    car_name: "Nissan",
    cost: 42958,
    model: "SUV",
    manufacturer: "Porsche",
    color: "White",
    num_doors: 3,
    cylinder_capacity: 7310,
    fuel_type: "Diesel",
    transmission: "Automatic",
    drive_type: "Rear-wheel drive",
    horsepower: 549,
  },
  {
    car_name: "Mercedes-Benz",
    cost: 86525,
    model: "Hatchback",
    manufacturer: "Chevrolet",
    color: "Red",
    num_doors: 5,
    cylinder_capacity: 3251,
    fuel_type: "Diesel",
    transmission: "Automatic",
    drive_type: "Front-wheel drive",
    horsepower: 906,
  },
  {
    car_name: "Toyota",
    cost: 75575,
    model: "Wagon",
    manufacturer: "Chevrolet",
    color: "Gray",
    num_doors: 5,
    cylinder_capacity: 4306,
    fuel_type: "Hybrid",
    transmission: "Manual",
    drive_type: "All-wheel drive",
    horsepower: 418,
  },
  {
    car_name: "BMW",
    cost: 90245,
    model: "Convertible",
    manufacturer: "BMW",
    color: "Green",
    num_doors: 5,
    cylinder_capacity: 6544,
    fuel_type: "Gasoline",
    transmission: "Manual",
    drive_type: "All-wheel drive",
    horsepower: 945,
  },
  {
    car_name: "Tesla",
    cost: 2224,
    model: "Sedan",
    manufacturer: "Chevrolet",
    color: "Silver",
    num_doors: 3,
    cylinder_capacity: 4324,
    fuel_type: "Electric",
    transmission: "Automatic",
    drive_type: "Rear-wheel drive",
    horsepower: 541,
  },
  {
    car_name: "Ford",
    cost: 50974,
    model: "Wagon",
    manufacturer: "BMW",
    color: "Yellow",
    num_doors: 3,
    cylinder_capacity: 3566,
    fuel_type: "Electric",
    transmission: "Manual",
    drive_type: "Rear-wheel drive",
    horsepower: 290,
  },
  {
    car_name: "Tesla",
    cost: 12374,
    model: "Coupe",
    manufacturer: "Honda",
    color: "Purple",
    num_doors: 3,
    cylinder_capacity: 3496,
    fuel_type: "Electric",
    transmission: "Automatic",
    drive_type: "All-wheel drive",
    horsepower: 638,
  },
  {
    car_name: "Nissan",
    cost: 2290,
    model: "Convertible",
    manufacturer: "Toyota",
    color: "Blue",
    num_doors: 3,
    cylinder_capacity: 3952,
    fuel_type: "Electric",
    transmission: "Manual",
    drive_type: "Rear-wheel drive",
    horsepower: 725,
  },
  {
    car_name: "Audi",
    cost: 21739,
    model: "Coupe",
    manufacturer: "BMW",
    color: "Red",
    num_doors: 3,
    cylinder_capacity: 7139,
    fuel_type: "Diesel",
    transmission: "Manual",
    drive_type: "All-wheel drive",
    horsepower: 88,
  },
  {
    car_name: "Tesla",
    cost: 62601,
    model: "Truck",
    manufacturer: "Ford",
    color: "Gray",
    num_doors: 4,
    cylinder_capacity: 1777,
    fuel_type: "Hybrid",
    transmission: "Manual",
    drive_type: "Rear-wheel drive",
    horsepower: 374,
  },
  {
    car_name: "Mercedes-Benz",
    cost: 51477,
    model: "Hatchback",
    manufacturer: "Porsche",
    color: "Gray",
    num_doors: 2,
    cylinder_capacity: 6272,
    fuel_type: "Diesel",
    transmission: "Manual",
    drive_type: "Rear-wheel drive",
    horsepower: 301,
  },
  {
    car_name: "Audi",
    cost: 2340,
    model: "Sedan",
    manufacturer: "Audi",
    color: "Blue",
    num_doors: 2,
    cylinder_capacity: 7547,
    fuel_type: "Diesel",
    transmission: "Automatic",
    drive_type: "All-wheel drive",
    horsepower: 990,
  },
  {
    car_name: "Ford",
    cost: 82762,
    model: "Truck",
    manufacturer: "Honda",
    color: "Orange",
    num_doors: 3,
    cylinder_capacity: 1233,
    fuel_type: "Gasoline",
    transmission: "Manual",
    drive_type: "All-wheel drive",
    horsepower: 574,
  },
  {
    car_name: "Chevrolet",
    cost: 81353,
    model: "Sedan",
    manufacturer: "Ford",
    color: "Gray",
    num_doors: 4,
    cylinder_capacity: 7250,
    fuel_type: "Electric",
    transmission: "Manual",
    drive_type: "Rear-wheel drive",
    horsepower: 848,
  },
  {
    car_name: "Tesla",
    cost: 6456,
    model: "Truck",
    manufacturer: "Porsche",
    color: "Black",
    num_doors: 2,
    cylinder_capacity: 7284,
    fuel_type: "Electric",
    transmission: "Manual",
    drive_type: "Rear-wheel drive",
    horsepower: 482,
  },
  {
    car_name: "Ford",
    cost: 53906,
    model: "Truck",
    manufacturer: "Ford",
    color: "White",
    num_doors: 2,
    cylinder_capacity: 3999,
    fuel_type: "Electric",
    transmission: "Automatic",
    drive_type: "Rear-wheel drive",
    horsepower: 351,
  },
  {
    car_name: "Mercedes-Benz",
    cost: 89483,
    model: "Convertible",
    manufacturer: "Honda",
    color: "Orange",
    num_doors: 3,
    cylinder_capacity: 6012,
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drive_type: "Front-wheel drive",
    horsepower: 504,
  },
  {
    car_name: "Mercedes-Benz",
    cost: 2403,
    model: "Truck",
    manufacturer: "Nissan",
    color: "Silver",
    num_doors: 4,
    cylinder_capacity: 3118,
    fuel_type: "Diesel",
    transmission: "Automatic",
    drive_type: "Rear-wheel drive",
    horsepower: 687,
  },
  {
    car_name: "Toyota",
    cost: 85539,
    model: "SUV",
    manufacturer: "Ford",
    color: "Blue",
    num_doors: 4,
    cylinder_capacity: 3042,
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drive_type: "All-wheel drive",
    horsepower: 256,
  },
  {
    car_name: "Honda",
    cost: 95579,
    model: "Wagon",
    manufacturer: "Chevrolet",
    color: "Yellow",
    num_doors: 3,
    cylinder_capacity: 6108,
    fuel_type: "Hybrid",
    transmission: "Manual",
    drive_type: "Front-wheel drive",
    horsepower: 721,
  },
  {
    car_name: "Nissan",
    cost: 74623,
    model: "Wagon",
    manufacturer: "Ford",
    color: "Blue",
    num_doors: 5,
    cylinder_capacity: 7696,
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drive_type: "Rear-wheel drive",
    horsepower: 338,
  },
  {
    car_name: "Porsche",
    cost: 28421,
    model: "Sedan",
    manufacturer: "Nissan",
    color: "Black",
    num_doors: 3,
    cylinder_capacity: 1745,
    fuel_type: "Electric",
    transmission: "Automatic",
    drive_type: "Rear-wheel drive",
    horsepower: 972,
  },
  {
    car_name: "Audi",
    cost: 92100,
    model: "Coupe",
    manufacturer: "Mercedes-Benz",
    color: "Yellow",
    num_doors: 4,
    cylinder_capacity: 5233,
    fuel_type: "Hybrid",
    transmission: "Automatic",
    drive_type: "Front-wheel drive",
    horsepower: 936,
  },
  {
    car_name: "Mercedes-Benz",
    cost: 56498,
    model: "Coupe",
    manufacturer: "BMW",
    color: "Purple",
    num_doors: 5,
    cylinder_capacity: 4617,
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drive_type: "Front-wheel drive",
    horsepower: 894,
  },
  {
    car_name: "Chevrolet",
    cost: 89561,
    model: "SUV",
    manufacturer: "Porsche",
    color: "Red",
    num_doors: 3,
    cylinder_capacity: 2849,
    fuel_type: "Hybrid",
    transmission: "Manual",
    drive_type: "Front-wheel drive",
    horsepower: 952,
  },
  {
    car_name: "Audi",
    cost: 45365,
    model: "Truck",
    manufacturer: "Tesla",
    color: "Blue",
    num_doors: 5,
    cylinder_capacity: 6656,
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drive_type: "All-wheel drive",
    horsepower: 57,
  },
  {
    car_name: "Audi",
    cost: 48935,
    model: "Truck",
    manufacturer: "Honda",
    color: "Yellow",
    num_doors: 4,
    cylinder_capacity: 7206,
    fuel_type: "Electric",
    transmission: "Automatic",
    drive_type: "Rear-wheel drive",
    horsepower: 636,
  },
  {
    car_name: "Honda",
    cost: 10388,
    model: "SUV",
    manufacturer: "Ford",
    color: "Purple",
    num_doors: 3,
    cylinder_capacity: 5268,
    fuel_type: "Hybrid",
    transmission: "Manual",
    drive_type: "Front-wheel drive",
    horsepower: 467,
  },
  {
    car_name: "Ford",
    cost: 92221,
    model: "Wagon",
    manufacturer: "Nissan",
    color: "Yellow",
    num_doors: 4,
    cylinder_capacity: 3959,
    fuel_type: "Hybrid",
    transmission: "Manual",
    drive_type: "Rear-wheel drive",
    horsepower: 635,
  },
  {
    car_name: "Tesla",
    cost: 37110,
    model: "SUV",
    manufacturer: "Honda",
    color: "Orange",
    num_doors: 2,
    cylinder_capacity: 5734,
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drive_type: "Rear-wheel drive",
    horsepower: 618,
  },
  {
    car_name: "Porsche",
    cost: 58381,
    model: "Sedan",
    manufacturer: "Tesla",
    color: "Red",
    num_doors: 3,
    cylinder_capacity: 4369,
    fuel_type: "Electric",
    transmission: "Automatic",
    drive_type: "Front-wheel drive",
    horsepower: 384,
  },
  {
    car_name: "Ford",
    cost: 29427,
    model: "SUV",
    manufacturer: "Mercedes-Benz",
    color: "Purple",
    num_doors: 4,
    cylinder_capacity: 5256,
    fuel_type: "Electric",
    transmission: "Automatic",
    drive_type: "Front-wheel drive",
    horsepower: 90,
  },
  {
    car_name: "Chevrolet",
    cost: 8021,
    model: "Truck",
    manufacturer: "Tesla",
    color: "Gray",
    num_doors: 4,
    cylinder_capacity: 1087,
    fuel_type: "Diesel",
    transmission: "Manual",
    drive_type: "Rear-wheel drive",
    horsepower: 568,
  },
  {
    car_name: "Mercedes-Benz",
    cost: 23977,
    model: "Wagon",
    manufacturer: "Honda",
    color: "Blue",
    num_doors: 3,
    cylinder_capacity: 2625,
    fuel_type: "Electric",
    transmission: "Manual",
    drive_type: "Front-wheel drive",
    horsepower: 824,
  },
  {
    car_name: "Ford",
    cost: 35562,
    model: "Hatchback",
    manufacturer: "Toyota",
    color: "Blue",
    num_doors: 4,
    cylinder_capacity: 4844,
    fuel_type: "Hybrid",
    transmission: "Manual",
    drive_type: "Rear-wheel drive",
    horsepower: 369,
  },
  {
    car_name: "Honda",
    cost: 3541,
    model: "Truck",
    manufacturer: "Audi",
    color: "Red",
    num_doors: 4,
    cylinder_capacity: 7528,
    fuel_type: "Electric",
    transmission: "Automatic",
    drive_type: "Rear-wheel drive",
    horsepower: 357,
  },
  {
    car_name: "Audi",
    cost: 31824,
    model: "Truck",
    manufacturer: "Honda",
    color: "Yellow",
    num_doors: 2,
    cylinder_capacity: 7410,
    fuel_type: "Hybrid",
    transmission: "Manual",
    drive_type: "Rear-wheel drive",
    horsepower: 415,
  },
  {
    car_name: "Toyota",
    cost: 74528,
    model: "SUV",
    manufacturer: "Toyota",
    color: "Silver",
    num_doors: 5,
    cylinder_capacity: 7052,
    fuel_type: "Electric",
    transmission: "Manual",
    drive_type: "Rear-wheel drive",
    horsepower: 947,
  },
  {
    car_name: "Nissan",
    cost: 81951,
    model: "SUV",
    manufacturer: "Audi",
    color: "Green",
    num_doors: 2,
    cylinder_capacity: 2922,
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drive_type: "All-wheel drive",
    horsepower: 819,
  },
  {
    car_name: "Tesla",
    cost: 54852,
    model: "Convertible",
    manufacturer: "Tesla",
    color: "Red",
    num_doors: 4,
    cylinder_capacity: 6987,
    fuel_type: "Hybrid",
    transmission: "Automatic",
    drive_type: "Rear-wheel drive",
    horsepower: 315,
  },
  {
    car_name: "Tesla",
    cost: 47556,
    model: "Hatchback",
    manufacturer: "Chevrolet",
    color: "Red",
    num_doors: 2,
    cylinder_capacity: 3076,
    fuel_type: "Electric",
    transmission: "Manual",
    drive_type: "All-wheel drive",
    horsepower: 644,
  },
  {
    car_name: "Toyota",
    cost: 75499,
    model: "Coupe",
    manufacturer: "Chevrolet",
    color: "Orange",
    num_doors: 2,
    cylinder_capacity: 3126,
    fuel_type: "Hybrid",
    transmission: "Manual",
    drive_type: "All-wheel drive",
    horsepower: 168,
  },
  {
    car_name: "Porsche",
    cost: 57258,
    model: "Wagon",
    manufacturer: "Tesla",
    color: "Yellow",
    num_doors: 3,
    cylinder_capacity: 1112,
    fuel_type: "Electric",
    transmission: "Manual",
    drive_type: "All-wheel drive",
    horsepower: 338,
  },
  {
    car_name: "Audi",
    cost: 84760,
    model: "Truck",
    manufacturer: "BMW",
    color: "Gray",
    num_doors: 2,
    cylinder_capacity: 6766,
    fuel_type: "Diesel",
    transmission: "Automatic",
    drive_type: "Rear-wheel drive",
    horsepower: 158,
  },
  {
    car_name: "Chevrolet",
    cost: 56740,
    model: "SUV",
    manufacturer: "Audi",
    color: "Silver",
    num_doors: 2,
    cylinder_capacity: 5168,
    fuel_type: "Diesel",
    transmission: "Automatic",
    drive_type: "All-wheel drive",
    horsepower: 388,
  },
  {
    car_name: "Chevrolet",
    cost: 42193,
    model: "Wagon",
    manufacturer: "Audi",
    color: "White",
    num_doors: 5,
    cylinder_capacity: 2203,
    fuel_type: "Diesel",
    transmission: "Manual",
    drive_type: "All-wheel drive",
    horsepower: 350,
  },
  {
    car_name: "Chevrolet",
    cost: 35492,
    model: "Wagon",
    manufacturer: "Nissan",
    color: "Yellow",
    num_doors: 5,
    cylinder_capacity: 5614,
    fuel_type: "Diesel",
    transmission: "Automatic",
    drive_type: "Front-wheel drive",
    horsepower: 903,
  },
  {
    car_name: "Tesla",
    cost: 53167,
    model: "Hatchback",
    manufacturer: "Honda",
    color: "Red",
    num_doors: 3,
    cylinder_capacity: 5273,
    fuel_type: "Hybrid",
    transmission: "Manual",
    drive_type: "Rear-wheel drive",
    horsepower: 638,
  },
  {
    car_name: "Toyota",
    cost: 27900,
    model: "Truck",
    manufacturer: "Chevrolet",
    color: "Yellow",
    num_doors: 3,
    cylinder_capacity: 6894,
    fuel_type: "Electric",
    transmission: "Manual",
    drive_type: "Front-wheel drive",
    horsepower: 413,
  },
  {
    car_name: "BMW",
    cost: 22954,
    model: "SUV",
    manufacturer: "Nissan",
    color: "Black",
    num_doors: 5,
    cylinder_capacity: 7335,
    fuel_type: "Electric",
    transmission: "Automatic",
    drive_type: "All-wheel drive",
    horsepower: 314,
  },
  {
    car_name: "Toyota",
    cost: 29274,
    model: "Sedan",
    manufacturer: "Mercedes-Benz",
    color: "Blue",
    num_doors: 5,
    cylinder_capacity: 2377,
    fuel_type: "Gasoline",
    transmission: "Manual",
    drive_type: "Rear-wheel drive",
    horsepower: 524,
  },
  {
    car_name: "Porsche",
    cost: 50917,
    model: "Wagon",
    manufacturer: "BMW",
    color: "Green",
    num_doors: 4,
    cylinder_capacity: 5849,
    fuel_type: "Diesel",
    transmission: "Automatic",
    drive_type: "All-wheel drive",
    horsepower: 262,
  },
  {
    car_name: "Ford",
    cost: 24891,
    model: "Coupe",
    manufacturer: "Nissan",
    color: "Blue",
    num_doors: 4,
    cylinder_capacity: 5089,
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drive_type: "Rear-wheel drive",
    horsepower: 930,
  },
  {
    car_name: "Chevrolet",
    cost: 47559,
    model: "Wagon",
    manufacturer: "Audi",
    color: "Orange",
    num_doors: 4,
    cylinder_capacity: 3417,
    fuel_type: "Electric",
    transmission: "Automatic",
    drive_type: "Front-wheel drive",
    horsepower: 144,
  },
  {
    car_name: "Porsche",
    cost: 58943,
    model: "SUV",
    manufacturer: "Ford",
    color: "Green",
    num_doors: 2,
    cylinder_capacity: 2770,
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drive_type: "Rear-wheel drive",
    horsepower: 247,
  },
  {
    car_name: "Chevrolet",
    cost: 8165,
    model: "Sedan",
    manufacturer: "Porsche",
    color: "Gray",
    num_doors: 2,
    cylinder_capacity: 5033,
    fuel_type: "Hybrid",
    transmission: "Manual",
    drive_type: "Front-wheel drive",
    horsepower: 995,
  },
  {
    car_name: "Toyota",
    cost: 89154,
    model: "SUV",
    manufacturer: "Chevrolet",
    color: "Orange",
    num_doors: 4,
    cylinder_capacity: 1996,
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drive_type: "All-wheel drive",
    horsepower: 919,
  },
  {
    car_name: "Nissan",
    cost: 4926,
    model: "SUV",
    manufacturer: "BMW",
    color: "Red",
    num_doors: 5,
    cylinder_capacity: 4242,
    fuel_type: "Diesel",
    transmission: "Automatic",
    drive_type: "All-wheel drive",
    horsepower: 428,
  },
  {
    car_name: "Toyota",
    cost: 93977,
    model: "Hatchback",
    manufacturer: "Ford",
    color: "Yellow",
    num_doors: 3,
    cylinder_capacity: 4727,
    fuel_type: "Hybrid",
    transmission: "Automatic",
    drive_type: "Front-wheel drive",
    horsepower: 670,
  },
  {
    car_name: "Honda",
    cost: 5833,
    model: "Coupe",
    manufacturer: "Porsche",
    color: "White",
    num_doors: 4,
    cylinder_capacity: 3781,
    fuel_type: "Diesel",
    transmission: "Manual",
    drive_type: "Front-wheel drive",
    horsepower: 915,
  },
  {
    car_name: "Honda",
    cost: 5403,
    model: "Convertible",
    manufacturer: "Ford",
    color: "Red",
    num_doors: 4,
    cylinder_capacity: 4134,
    fuel_type: "Hybrid",
    transmission: "Manual",
    drive_type: "Front-wheel drive",
    horsepower: 817,
  },
  {
    car_name: "Toyota",
    cost: 37721,
    model: "Truck",
    manufacturer: "Toyota",
    color: "Black",
    num_doors: 5,
    cylinder_capacity: 4099,
    fuel_type: "Electric",
    transmission: "Manual",
    drive_type: "Front-wheel drive",
    horsepower: 726,
  },
  {
    car_name: "Toyota",
    cost: 4773,
    model: "Wagon",
    manufacturer: "Mercedes-Benz",
    color: "White",
    num_doors: 2,
    cylinder_capacity: 2992,
    fuel_type: "Hybrid",
    transmission: "Manual",
    drive_type: "All-wheel drive",
    horsepower: 396,
  },
  {
    car_name: "Porsche",
    cost: 82555,
    model: "Coupe",
    manufacturer: "Chevrolet",
    color: "Yellow",
    num_doors: 4,
    cylinder_capacity: 1767,
    fuel_type: "Gasoline",
    transmission: "Manual",
    drive_type: "Rear-wheel drive",
    horsepower: 815,
  },
  {
    car_name: "Porsche",
    cost: 39834,
    model: "Convertible",
    manufacturer: "BMW",
    color: "Green",
    num_doors: 5,
    cylinder_capacity: 1270,
    fuel_type: "Electric",
    transmission: "Manual",
    drive_type: "Front-wheel drive",
    horsepower: 134,
  },
  {
    car_name: "Audi",
    cost: 23750,
    model: "Coupe",
    manufacturer: "Honda",
    color: "Orange",
    num_doors: 4,
    cylinder_capacity: 5923,
    fuel_type: "Gasoline",
    transmission: "Manual",
    drive_type: "All-wheel drive",
    horsepower: 551,
  },
  {
    car_name: "Mercedes-Benz",
    cost: 55004,
    model: "Hatchback",
    manufacturer: "BMW",
    color: "Gray",
    num_doors: 4,
    cylinder_capacity: 7785,
    fuel_type: "Hybrid",
    transmission: "Manual",
    drive_type: "Front-wheel drive",
    horsepower: 292,
  },
  {
    car_name: "Tesla",
    cost: 90689,
    model: "Truck",
    manufacturer: "Toyota",
    color: "Orange",
    num_doors: 4,
    cylinder_capacity: 4056,
    fuel_type: "Diesel",
    transmission: "Manual",
    drive_type: "All-wheel drive",
    horsepower: 537,
  },
  {
    car_name: "Toyota",
    cost: 9449,
    model: "Convertible",
    manufacturer: "Toyota",
    color: "Silver",
    num_doors: 5,
    cylinder_capacity: 4554,
    fuel_type: "Electric",
    transmission: "Automatic",
    drive_type: "All-wheel drive",
    horsepower: 108,
  },
  {
    car_name: "Nissan",
    cost: 91997,
    model: "Convertible",
    manufacturer: "Honda",
    color: "Silver",
    num_doors: 5,
    cylinder_capacity: 2336,
    fuel_type: "Gasoline",
    transmission: "Manual",
    drive_type: "Front-wheel drive",
    horsepower: 702,
  },
  {
    car_name: "Tesla",
    cost: 52812,
    model: "Convertible",
    manufacturer: "Ford",
    color: "Orange",
    num_doors: 5,
    cylinder_capacity: 6804,
    fuel_type: "Gasoline",
    transmission: "Manual",
    drive_type: "Rear-wheel drive",
    horsepower: 307,
  },
  {
    car_name: "Tesla",
    cost: 47898,
    model: "Wagon",
    manufacturer: "Toyota",
    color: "Gray",
    num_doors: 4,
    cylinder_capacity: 2767,
    fuel_type: "Gasoline",
    transmission: "Manual",
    drive_type: "Rear-wheel drive",
    horsepower: 866,
  },
  {
    car_name: "Tesla",
    cost: 44926,
    model: "SUV",
    manufacturer: "Toyota",
    color: "Red",
    num_doors: 5,
    cylinder_capacity: 2248,
    fuel_type: "Diesel",
    transmission: "Automatic",
    drive_type: "All-wheel drive",
    horsepower: 704,
  },
  {
    car_name: "Mercedes-Benz",
    cost: 36696,
    model: "Wagon",
    manufacturer: "Chevrolet",
    color: "Black",
    num_doors: 3,
    cylinder_capacity: 2860,
    fuel_type: "Diesel",
    transmission: "Manual",
    drive_type: "Rear-wheel drive",
    horsepower: 951,
  },
  {
    car_name: "Tesla",
    cost: 63306,
    model: "Sedan",
    manufacturer: "Chevrolet",
    color: "White",
    num_doors: 2,
    cylinder_capacity: 4269,
    fuel_type: "Electric",
    transmission: "Automatic",
    drive_type: "Rear-wheel drive",
    horsepower: 198,
  },
  {
    car_name: "Chevrolet",
    cost: 26598,
    model: "Hatchback",
    manufacturer: "Tesla",
    color: "Orange",
    num_doors: 3,
    cylinder_capacity: 3055,
    fuel_type: "Hybrid",
    transmission: "Automatic",
    drive_type: "Front-wheel drive",
    horsepower: 780,
  },
  {
    car_name: "Tesla",
    cost: 89973,
    model: "Convertible",
    manufacturer: "Tesla",
    color: "Silver",
    num_doors: 5,
    cylinder_capacity: 6226,
    fuel_type: "Gasoline",
    transmission: "Manual",
    drive_type: "All-wheel drive",
    horsepower: 382,
  },
  {
    car_name: "Nissan",
    cost: 51453,
    model: "SUV",
    manufacturer: "Porsche",
    color: "Green",
    num_doors: 2,
    cylinder_capacity: 7879,
    fuel_type: "Diesel",
    transmission: "Automatic",
    drive_type: "Rear-wheel drive",
    horsepower: 511,
  },
  {
    car_name: "Chevrolet",
    cost: 47562,
    model: "Coupe",
    manufacturer: "Ford",
    color: "Silver",
    num_doors: 3,
    cylinder_capacity: 1619,
    fuel_type: "Diesel",
    transmission: "Automatic",
    drive_type: "All-wheel drive",
    horsepower: 608,
  },
  {
    car_name: "Audi",
    cost: 90866,
    model: "SUV",
    manufacturer: "Ford",
    color: "Green",
    num_doors: 3,
    cylinder_capacity: 2013,
    fuel_type: "Diesel",
    transmission: "Manual",
    drive_type: "All-wheel drive",
    horsepower: 68,
  },
  {
    car_name: "Audi",
    cost: 33490,
    model: "Convertible",
    manufacturer: "Chevrolet",
    color: "Orange",
    num_doors: 4,
    cylinder_capacity: 7483,
    fuel_type: "Diesel",
    transmission: "Manual",
    drive_type: "All-wheel drive",
    horsepower: 674,
  },
  {
    car_name: "Porsche",
    cost: 11905,
    model: "SUV",
    manufacturer: "Chevrolet",
    color: "Purple",
    num_doors: 5,
    cylinder_capacity: 1866,
    fuel_type: "Electric",
    transmission: "Automatic",
    drive_type: "All-wheel drive",
    horsepower: 659,
  },
  {
    car_name: "Nissan",
    cost: 97675,
    model: "SUV",
    manufacturer: "BMW",
    color: "Blue",
    num_doors: 4,
    cylinder_capacity: 1009,
    fuel_type: "Hybrid",
    transmission: "Automatic",
    drive_type: "Front-wheel drive",
    horsepower: 84,
  },
  {
    car_name: "Porsche",
    cost: 50288,
    model: "Convertible",
    manufacturer: "Toyota",
    color: "Red",
    num_doors: 2,
    cylinder_capacity: 3902,
    fuel_type: "Diesel",
    transmission: "Manual",
    drive_type: "All-wheel drive",
    horsepower: 476,
  },
  {
    car_name: "Mercedes-Benz",
    cost: 67540,
    model: "Wagon",
    manufacturer: "Porsche",
    color: "Red",
    num_doors: 2,
    cylinder_capacity: 3139,
    fuel_type: "Hybrid",
    transmission: "Manual",
    drive_type: "Rear-wheel drive",
    horsepower: 787,
  },
];
